spring:
  servlet:
    multipart:
      location: /Users/hwangjuhui/Documents/lecture/10_spring/lecture-source/02_spring-web-mvc/chap06-file-upload
      max-file-size: 10MB
      max-request-size: 10MB
